### ISSUE TITLE
scipy required in setup.py

### ISSUE THREAD

**Issue by tyronechen** [Shamir-Lab/MONET#1]
Dear Dr Shamir,

[I was interested in your preprint on MONET](https://www.biorxiv.org/content/10.1101/2020.02.21.960062v1) and wanted to try out the tool. After installing with `python setup.py install`, I got a `ModuleNotFoundError: No module named 'scipy'` when running the brief example code in the `README`.

Adding `scipy` to the list of required packages in `setup.py` appears to fix the install, shown in the below code block:

```
from setuptools import setup

setup(name='monet',
      version=0.1,
      author='Nimrod Rappoport',
      url='https://github.com/Shamir-Lab/MONET',
      description='python implementation of the MONET algorithm for multi-omic module detection',
      license='GPL-3.0',
      python_requires='>3.0.0',
      install_requires=['numpy', 'pandas', 'networkx', 'scipy']
)
```

For conda users, `conda` will write the package to a different location so `conda install scipy` wont work.

**Comment by nimrodrap** [comment]
Thanks, we added scipy to the dependencies.
